language: python
sudo: false
jobs:
    include:
        - python: "3.6"
        - python: "3.7"
          dist: xenial
install:
    - pip install -r requirements-dev.txt
script:
    - pytest -k 'not windows'
